### ISSUE TITLE
Pinned Gmail button has bad behavior in a new window

### ISSUE THREAD

**Issue by sclark39** [abrizuela/pinned_gmail#8]
When I'm in a new window that doesn't have a pinned Gmail tab, after having already opened a tab in a different window, the "Pinned Gmail" button feels like it's not doing anything. It looks like it is trying to switch to the correct tab in the other window which isn't the one that I'm working in and may be covered up with other windows (so generally isn't very useful). It would be better for it to open a new tab in the new window.

**Repro:**

1. Open Firefox
2. Click "Pinned Gmail" icon - Gmail Tab opens and is pinned (good!)
3. Make new Firefox window, and maximize it so you can't see the original window.
4. Click "Pinned Gmail" icon - Nothing appears to happens. (bad 😢)

**Expected Behavior:**
A new Gmail tab should always be opened and pinned if one doesn't exist in the current window, or switched to it if it does.

**Comment by sclark39** [comment]
It looks like it's pretty easy to modify to support this because the `browser.tabs.query` can take a `windowId` specifier. 

I decided to play a bit with this and made a function that cycles between all open gmail tabs and your last non-gmail tab, contained to the current window. Feel free to pull anything you want from it.

https://gist.github.com/sclark39/c10b1de38084ab82e76bd07fe829fb40

**Comment by abrizuela** [comment]
Hi Skyler! Thanks for pointing me out the bug! I already had a solution implemented for another addons but it seems I forgot to do it here. Version 2.4.0 will fix that soon.
